# Generated by Django 6.0.3 on 2026-04-02 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 2, 9, 45, 40, 321950, tzinfo=datetime.timezone.utc)),
        ),
    ]
