# Generated by Django 6.0.3 on 2026-04-02 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='allProducts/'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 2, 10, 8, 58, 361339, tzinfo=datetime.timezone.utc)),
        ),
    ]
